### ISSUE TITLE
Conflict with Gravity Forms custom fields

### ISSUE THREAD

**Issue by ibdf** [DannyvanHolten/acf-gravityforms-add-on#25] opened 2018-07-11 14:31 UTC
I'm registering custom fields to Gravity Forms by extending the GF_Field class.  See https://docs.gravityforms.com/gf_field/

For some reason whenever I have the ACF Gravityforms Addon activated the input of custom field I created using the method `get_field_input` won't render. It looks like it doesn't get triggered.

To confirm this, I installed a new Wordpress site (using default theme), installed Gravity Forms, and the code for the custom field. Everything worked fine until I installed this addon. Deactivating the addon will fix the issue.

**Comment by ibdf** [comment] 2018-07-11 15:56
I was trying to track down this issue, as it looks like there are a couple of other tickets opened where a similar issue is happening (custom fields inputs are not rendering)

I don't know why yet, but in the Notices class the `$this->forms = GFAPI::get_forms();` assignment on line 19 seems to break the GF field input rendering. After commenting it out or setting it to an empty array, I am able to render my field. I'm not sure why it's happening, but that's the only part of the plugin that seems to cause this issue, even though you use the same method in Field.php

**Comment by richardW8k** [comment] 2018-07-11 16:21
Add-ons which add new field types usually include their class which extends `GF_Field` on the `plugins_loaded`, `gform_loaded`, or `init` hook. 

If `Notices` is calling `GFAPI::get_forms()` before the hook which is including the field class fires then the form object will be cached at a point in time when the field could only be instantiated using the basic `GF_Field` object which will prevent the field being functioning as intended.

**Comment by ibdf** [comment] 2018-07-12 15:27
@richardW8k thanks for this info. So it looks like the admin_notices hook is not a good place to call get_forms. For now, my solution is to comment out that line, I don't need the notices.

**Comment by BufferOverNo** [comment] 2018-08-09 11:46
So, doing the above worked, however, it stops the Forms option showing on ACF in the relation field.

**Comment by BufferOverNo** [comment] 2018-08-16 08:38
Please use this instead, as it the notices should be ran on admin level/backend level.
add_action('admin_init', function() {
//Code here
});

**Comment by eboels** [comment] 2018-08-20 10:06
I have this conflict with survey add-on.
This last solution works for me.
Will it be in the next update?

**Comment by remcotolsma** [comment] 2020-03-20 12:56
This issue is also causing issues with the Pronamic Pay integration for Gravity Forms. I don't think it's best practice to load all Gravity Forms directly when this plugin file is included by WordPress:

https://github.com/WordPress/WordPress/blob/5.3/wp-settings.php#L360

@DannyvanHolten can we expect a fix for this issue?

**Comment by RupW** [comment] 2020-03-20 23:05
There is a commit now that looks like it fixes this? da3bc74e84257a8a7028a50a5224d3e48b5b6eca but it doesn't look like it's been pushed to the WordPress SVN.

FWIW [here's my fixed version](https://github.com/RupW/acf-gravityforms-add-on). Apologies I never got around to tidying it up and submitting it back. Will compare what's here and what I did when I get a chance?

**Comment by markhowellsmead** [comment] 2020-09-16 17:43
@ibdf @richardW8k @jgarib @bufferoverno @eboels @remcotolsma @RupW I have manually merged in a number of pending code amendments. Due to the age of the change requests, I would greatly appreciate it if you could install 1.2.5 from Github and let me know if the issues mentioned here are resolved. Many thanks!

**Comment by markhowellsmead** [comment] 2021-01-12 09:48
Version 1.2.6 is now released.

**Closed by markhowellsmead** 2021-01-12 09:48 UTC
