### ISSUE TITLE
Conflict with GF Coupon add on Plugin

### ISSUE THREAD

**Issue by Pixelsmith** [DannyvanHolten/acf-gravityforms-add-on#23] opened 2018-04-26 18:29 UTC
Hi Danny,

Your plugin is awesome, but I've run into a conflict with it.

I'm using the Gravity Forms Coupon Add-On (https://www.gravityforms.com/add-ons/coupons/) and when I install the ACF/GF Add-On the coupon input field no longer appears in my forms. When I disable AFC/GF it appears again.

Edit: I also confirmed this bug is causing the 'Username' field to disappear.

I understand that you may not guarantee performance with optional add-ons, but I thought I'd let you know about the conflict, as it took me awhile to suss it out.

Thanks,
Adam

**Comment by nathanp** [comment] 2019-08-30 21:08
@Pixelsmith I may have found a temporary workaround. In the `/resources/Init.php` file, I commented out line 10:
```$this->addNotices();```

This seems to have solved it for me, but I don't know if this will impact other areas of the plugin's functionality. So far it seems to be working for me.

**Comment by n8kowald** [comment] 2019-09-20 01:01
I had a plugin conflict using Gravity Perks Nested Forms plugin: https://gravitywiz.com/documentation/gravity-forms-nested-forms

`Fatal error: Uncaught Error: Call to undefined method GF_Field::get_item_label() in ...site/wp-content/plugins/gp-nested-forms/class-gp-nested-forms.php:1633`

My bug and your bug @Pixelsmith is caused by the `GFAPI::get_forms()` call in the Notices constructor running too early, which is why commenting out `$this->addNotices()` fixes it as suggested by @nathanp.

`$this->addNotices()` is getting and caching form meta fields too early (as soon as the plugin code is executed). Before our plugins have registered their own custom fields.
When our Gravity Form should be loading a custom field - in my case `GP_Field_Nested_Form` - it loads a `GF_Field` instead which causes issues as the custom field code is not defined.

Here's a pull request that fixes the issue:
https://github.com/DannyvanHolten/acf-gravityforms-add-on/pull/29

**Comment by markhowellsmead** [comment] 2020-09-16 17:40
@n8kowald @Pixelsmith @nathanp @joshlewis I have manually merged in a number of pending code amendments. Due to the age of the change requests, I would greatly appreciate it if you could install 1.2.5 from Github and let me know if the issues mentioned here are resolved. Many thanks!

**Comment by markhowellsmead** [comment] 2021-01-12 09:48
Version 1.2.6 is now released.

**Closed by markhowellsmead** 2021-01-12 09:48 UTC
